spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:8080"
              - "http://localhost:8761"
            allowedHeaders:
              - "Content-Type"
              - "text/plain"
              - "Authorization"
              - "Access-Control-Allow-Origin"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
      routes:
        - id: USER-HANDLE-API
          uri: lb://USER-HANDLE-API
          predicates:
            - Path=/user-handle/**

          filters:
            - AuthenticationFilter

        - id: ECHIKTSA-BACKEND
          uri: lb://ECHIKTSA-BACKEND
          predicates:
            - Path=/echikitsa-backend/**
          filters:
            - AuthenticationFilter

        - id: USER-FILE-API
          uri: lb://USER-FILE-API
          predicates:
            - Path=/file-handle/**
          filters:
            - AuthenticationFilter


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /user-handle/v3/api-docs
        name: user-handle
      - url: /echikitsa-backend/v3/api-docs
        name: echikitsa-backend
      - url: /file-handle/v3/api-docs
        name: file-handle

#To access Swagger Documentation
#https://localhost:8083/webjars/swagger-ui/index.html